//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interlibros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroEnTransaccion
    {
        public int idTransaccion { get; set; }
        public int idLibro { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
