//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interlibros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroEnCarro
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idLibro { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
