//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interlibros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idLibreria { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Librerias Librerias { get; set; }
        public virtual LibroEnTransaccion LibroEnTransaccion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
